---
title: "Assignment 6"
author: "Max Wagner"
date: "March 7, 2016"
header-includes:
   - \usepackage{bbm}
output:
  pdf_document: default
  html_document:
    highlight: espresso
    theme: flatly
---
***

####PS1.

####1.

The number of outcomes is `r 6*6*6` for a fair dice rolled three times.

####2.

The potential outcomes for two rolls is `r 6*6`, and there are 2 potential rolls that give a sum of 3. That means the chances of getting a sum of 3 is `r 2/36`.

####3.

.

For 25 people in a room:

```{r}
pbirthday(25) # There's a base function that does this, weirdly enough
1 - prod(1 - (0:24)/365) # testing with my own math
```

For 50 people in a room:

```{r}
pbirthday(50) # There's a base function that does this, weirdly enough
1 - prod(1 - (0:49)/365) # testing with my own math
```

####PS2.

For part 1 we are looking at just one word, so it's not too complicated.

```{r}
library("stringr")

singleProb <- function(corpus){
  corp <- iconv(corpus, "UTF-8", "ASCII", sub="?") # convert to ASCII in order to use gsub
  corp <- gsub("[^[:alpha:]]", "", corp) # remove punctuation
  corp <- tolower(corp) # make lowercase
  corp <- corp[corp != ''] # remove first blank line
  prob <- as.data.frame(table(corp)) # make it a data frame
  prob$prob <- prob$Freq / sum(prob$Freq) # add a column to sort by
  return(prob)
}

corpus <- scan('https://raw.githubusercontent.com/maxwagner/605/master/assign/assign6.sample.txt', character(0), quote=NULL, encoding = "UTF-8")
probability <- singleProb(corpus)
head(probability) # sample output
```

The two word one is a bit more complicated.

```{r}
doubleProb <- function(corpus, word1, word2) {
  corp <- iconv(corpus, "UTF-8", "ASCII", sub="?") # convert to ASCII in order to use gsub
  corp <- gsub("[^[:alpha:]]", "", corp) # remove punctuation
  corp <- tolower(corp) # make lowercase
  corp <- corp[corp != ''] # remove first blank line
  
  prob_frame <- data.frame(corp) # make a frame with just words in it
  prob_frame$prev <- c(NA, corp[1:length(corp)-1]) # check whats previous to the word
  prob_frame <- prob_frame[2:nrow(prob_frame),] # check whats after the word

  prob_frame$match <- ifelse((prob_frame$corp == word1 & prob_frame$prev == word2) | (prob_frame$corp == word2 & prob_frame$prev == word1),1,0)
  return(sum(prob_frame$match) / nrow(prob_frame))
}

corpus <- scan('https://raw.githubusercontent.com/maxwagner/605/master/assign/assign6.sample.txt', character(0), quote=NULL, encoding = "UTF-8")
doubleProb(corpus, "to", "the") # sample output 1
doubleProb(corpus, "to", "cat") # sample output 2
```